import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Shield,LayoutDashboard,ClipboardCheck,Users,LockKeyhole,AlertTriangle,HeartPulse,CalendarDays,Activity,ChevronRight,CheckCircle2,Clock3,Brain,Menu,X,LogOut} from 'lucide-react';
import './styles.css';

const initialPersonnel=[
 {id:'CR-1042',name:'A. Sharma',unit:'Alpha Unit',deployment:'High-intensity',leave:2,duty:9,wellness:62,risk:'Elevated',last:'Today'},
 {id:'CR-1187',name:'R. Singh',unit:'Bravo Unit',deployment:'Routine',leave:5,duty:7,wellness:81,risk:'Low',last:'Yesterday'},
 {id:'CR-1214',name:'V. Kumar',unit:'Charlie Unit',deployment:'Extended',leave:1,duty:11,wellness:48,risk:'High',last:'Today'},
 {id:'CR-1321',name:'P. Verma',unit:'Delta Unit',deployment:'Routine',leave:4,duty:8,wellness:76,risk:'Low',last:'2 days ago'}
];

function riskFromScore(score){if(score>=75)return ['High','high'];if(score>=50)return ['Elevated','medium'];return ['Low','low'];}
function App(){
 const [page,setPage]=useState('dashboard'); const [mobile,setMobile]=useState(false); const [role,setRole]=useState('Welfare Officer');
 const [personnel,setPersonnel]=useState(initialPersonnel); const [submitted,setSubmitted]=useState(false);
 const [form,setForm]=useState({sleep:3,mood:3,energy:3,workload:3,concern:'No immediate concern'});
 const stats=useMemo(()=>({total:personnel.length,elevated:personnel.filter(x=>x.risk==='Elevated').length,high:personnel.filter(x=>x.risk==='High').length,avg:Math.round(personnel.reduce((a,b)=>a+b.wellness,0)/personnel.length)}),[personnel]);
 const nav=[['dashboard','Dashboard',LayoutDashboard],['assessment','Wellness Check-in',ClipboardCheck],['personnel','Personnel',Users],['privacy','Privacy & Access',LockKeyhole]];
 function submit(){const raw=(form.sleep+form.mood+form.energy+form.workload)*6; const score=Math.max(0,100-raw); const [risk]=riskFromScore(score); setSubmitted(true); setPersonnel(p=>p.map((x,i)=>i===0?{...x,wellness:score,risk,last:'Just now'}:x));}
 return <div className="app">
  <header className="topbar"><button className="iconbtn menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div className="brand"><div className="brandmark"><Shield size={21}/></div><div><b>RakshakWell</b><span>Personnel Welfare Intelligence</span></div></div><div className="topright"><select value={role} onChange={e=>setRole(e.target.value)}><option>Welfare Officer</option><option>Commander</option><option>Personnel</option></select><div className="avatar">WO</div></div></header>
  <div className="layout">
   <aside className={mobile?'sidebar open':'sidebar'}><div className="side-label">WORKSPACE</div>{nav.map(([key,label,Icon])=><button key={key} className={page===key?'nav active':'nav'} onClick={()=>{setPage(key);setMobile(false)}}><Icon size={18}/>{label}</button>)}<div className="side-bottom"><div className="privacy-mini"><LockKeyhole size={16}/><div><b>Privacy first</b><small>Welfare use only</small></div></div><button className="logout"><LogOut size={16}/> Sign out</button></div></aside>
   <main className="main">
    {page==='dashboard'&&<Dashboard stats={stats} personnel={personnel} onAssessment={()=>setPage('assessment')} />}
    {page==='assessment'&&<Assessment form={form} setForm={setForm} submit={submit} submitted={submitted} />}
    {page==='personnel'&&<Personnel personnel={personnel}/>} 
    {page==='privacy'&&<Privacy role={role}/>} 
   </main>
  </div>
 </div>
}
function Dashboard({stats,personnel,onAssessment}){return <>
 <div className="hero"><div><div className="eyebrow">WELFARE OPERATIONS • LIVE DEMO</div><h1>Personnel Wellness Dashboard</h1><p>Early indicators, welfare trends and intervention signals — designed for supportive action, not disciplinary decisions.</p></div><button className="primary" onClick={onAssessment}><ClipboardCheck size={17}/> Start wellness check-in</button></div>
 <div className="notice"><Shield size={19}/><div><b>Confidential welfare workspace</b><span>Only authorized roles can access identifiable information. Risk indicators are support signals, not diagnoses.</span></div></div>
 <div className="stats"><Stat icon={Users} label="Personnel monitored" value={stats.total} sub="Active demo records"/><Stat icon={HeartPulse} label="Avg. wellness" value={stats.avg+'%'} sub="Self-report + workload signals"/><Stat icon={AlertTriangle} label="Elevated signals" value={stats.elevated} sub={stats.high+' high signal'} warn/><Stat icon={Activity} label="Check-ins" value="86%" sub="Last 30 days"/></div>
 <section className="grid2"><div className="card"><div className="cardhead"><div><h2>Welfare signal overview</h2><p>Current personnel requiring attention</p></div><button className="textbtn">View all <ChevronRight size={15}/></button></div>{personnel.map(p=><PersonRow key={p.id} p={p}/>)}</div><div className="card"><div className="cardhead"><div><h2>Recommended actions</h2><p>Supportive next steps</p></div></div><Action icon={Clock3} title="Review duty load" text="2 personnel show extended duty patterns."/><Action icon={CalendarDays} title="Consider leave discussion" text="1 person has a low leave frequency signal."/><Action icon={HeartPulse} title="Offer confidential check-in" text="2 personnel may benefit from a welfare conversation."/><div className="safe"><CheckCircle2 size={17}/><span>Recommendations require human review before any action.</span></div></div></section>
 <div className="footer-note"><LockKeyhole size={15}/> Demo data only • No medical diagnosis • Access is role-based</div>
 </>}
function Stat({icon:Icon,label,value,sub,warn}){return <div className="stat"><div className={warn?'staticon warn':'staticon'}><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong><small>{sub}</small></div></div>}
function PersonRow({p}){return <div className="personrow"><div className="person"><div className="pavatar">{p.name.split(' ').map(x=>x[0]).join('')}</div><div><b>{p.name}</b><span>{p.id} • {p.unit}</span></div></div><div className="metric"><span>Wellness</span><b>{p.wellness}%</b></div><div className="metric"><span>Duty</span><b>{p.duty}h/day</b></div><span className={'badge '+p.risk.toLowerCase()}>{p.risk}</span></div>}
function Action({icon:Icon,title,text}){return <div className="action"><div className="actionicon"><Icon size={17}/></div><div><b>{title}</b><span>{text}</span></div><ChevronRight size={16}/></div>}
function Assessment({form,setForm,submit,submitted}){return <div className="page"><div className="pagehead"><div><div className="eyebrow">VOLUNTARY SELF-ASSESSMENT</div><h1>Wellness Check-in</h1><p>A short private check-in to help identify support needs.</p></div><div className="secure"><LockKeyhole size={16}/> Encrypted & confidential</div></div><div className="assessment"><div className="card formcard"><div className="formintro"><Brain size={23}/><div><h2>How have you been feeling?</h2><p>There are no right or wrong answers. Your responses are intended for welfare support.</p></div></div>{[['sleep','Sleep quality'],['mood','Mood & emotional balance'],['energy','Energy level'],['workload','Perceived workload']].map(([key,label])=><label className="range"><div><b>{label}</b><span>{['Very low','Low','Okay','Good','Very good'][form[key]-1]}</span></div><input type="range" min="1" max="5" value={form[key]} onChange={e=>setForm({...form,[key]:+e.target.value})}/><div className="ticks"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span></div></label>)}<label className="field"><b>Anything you want welfare staff to know?</b><textarea placeholder="Optional — share only what you are comfortable sharing" value={form.concern} onChange={e=>setForm({...form,concern:e.target.value})}/></label><button className="primary wide" onClick={submit}><CheckCircle2 size={17}/> Submit confidential check-in</button>{submitted&&<div className="success"><CheckCircle2 size={18}/><div><b>Check-in recorded for this demo</b><span>A support signal was generated for authorized welfare review.</span></div></div>}</div><div className="card explainer"><h3>How the demo works</h3><Step n="01" title="Self-report" text="Personnel voluntarily share wellness indicators."/><Step n="02" title="Risk signal" text="Demo analytics combine responses with workload context."/><Step n="03" title="Human review" text="Authorized welfare staff review context before action."/><Step n="04" title="Support" text="The system suggests welfare-oriented interventions."/><div className="redflag"><AlertTriangle size={16}/><span>Signals are indicative only and should never be treated as a diagnosis.</span></div></div></div></div>}
function Step({n,title,text}){return <div className="step"><span>{n}</span><div><b>{title}</b><small>{text}</small></div></div>}
function Personnel({personnel}){const [q,setQ]=useState('');const rows=personnel.filter(p=>(p.name+p.id+p.unit).toLowerCase().includes(q.toLowerCase()));return <div className="page"><div className="pagehead"><div><div className="eyebrow">AUTHORIZED VIEW</div><h1>Personnel</h1><p>Demo personnel records with welfare-oriented indicators.</p></div></div><div className="card tablecard"><div className="tabletools"><input placeholder="Search personnel..." value={q} onChange={e=>setQ(e.target.value)}/><select><option>All units</option><option>Alpha Unit</option><option>Bravo Unit</option></select></div><div className="tablewrap"><table><thead><tr><th>Personnel</th><th>Deployment</th><th>Wellness</th><th>Duty</th><th>Leave</th><th>Signal</th><th>Last check-in</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><b>{p.name}</b><small>{p.id} • {p.unit}</small></td><td>{p.deployment}</td><td><div className="progress"><i style={{width:p.wellness+'%'}}/></div><small>{p.wellness}%</small></td><td>{p.duty}h</td><td>{p.leave} days</td><td><span className={'badge '+p.risk.toLowerCase()}>{p.risk}</span></td><td>{p.last}</td></tr>)}</tbody></table></div></div></div>}
function Privacy({role}){return <div className="page"><div className="pagehead"><div><div className="eyebrow">GOVERNANCE</div><h1>Privacy & Access</h1><p>Privacy safeguards are part of the welfare workflow, not an afterthought.</p></div></div><div className="privacygrid"><div className="card"><h2>Current demo role</h2><div className="rolebig"><Shield size={23}/><div><b>{role}</b><span>Role-based access context</span></div></div><div className="perm"><CheckCircle2/> View welfare signals</div><div className="perm"><CheckCircle2/> Review recommendations</div><div className="perm"><CheckCircle2/> Support check-in workflow</div><div className="perm muted"><LockKeyhole/> Raw sensitive data restricted</div></div><div className="card"><h2>Protection principles</h2><div className="guard"><LockKeyhole/><div><b>Data minimization</b><span>Only relevant welfare and organizational indicators are used.</span></div></div><div className="guard"><Shield/><div><b>Role-based access</b><span>Identifiable information is limited to authorized welfare workflows.</span></div></div><div className="guard"><Users/><div><b>Human-in-the-loop</b><span>AI signals support review; they do not autonomously decide interventions.</span></div></div><div className="guard"><HeartPulse/><div><b>Welfare-first purpose</b><span>The system is intended for support rather than disciplinary action.</span></div></div></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);